name: BUILD APK NEWWW

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          cache-read-only: false
      
      - name: Configure Gradle for Parallel Builds
        run: |
          mkdir -p ~/.gradle
          cat > ~/.gradle/gradle.properties << EOF
          org.gradle.parallel=true
          org.gradle.workers.max=4
          org.gradle.caching=true
          org.gradle.configureondemand=true
          org.gradle.jvmargs=-Xmx4g -XX:MaxMetaspaceSize=1g -XX:+HeapDumpOnOutOfMemoryError -XX:+UseParallelGC
          android.useAndroidX=true
          android.enableJetifier=true
          kotlin.incremental=true
          kotlin.parallel.tasks.in.project=true
          EOF
      
      - name: Generate Temporary Release Keystore
        run: |
          keytool -genkeypair \
            -dname "CN=GitHub Actions, OU=Automated Build, O=Open Source, L=Unknown, ST=Unknown, C=US" \
            -keystore release.keystore \
            -alias release-alias \
            -storepass insecure_password_123 \
            -keypass insecure_password_123 \
            -keyalg RSA -keysize 2048 -validity 1
      
      - name: Make Gradle wrapper executable
        run: chmod +x ./gradlew
      
      - name: Build (assembleRelease) using wrapper
        run: ./gradlew assembleRelease --parallel --max-workers=4 --build-cache --configuration-cache
        env:
          RELEASE_KEYSTORE: release.keystore
          RELEASE_KEYSTORE_PASSWORD: "insecure_password_123"
          RELEASE_KEY_ALIAS: "release-alias"
          RELEASE_KEY_PASSWORD: "insecure_password_123"
      
      - name: Upload Release APK as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: release-apk-${{ github.run_number }}
          path: build/outputs/apk/release/*.apk
